name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["13.x"]
        mongodb-version: ["4.2.3"]

    steps:
      - name: Launch MongoDB
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: ${{ matrix.mongodb-version }}
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp keys/jwtRS256.key.example keys/jwtRS256.key
      - run: cp keys/jwtRS256.key.pub.example keys/jwtRS256.key.pub
      - run: npm install
      - run: NODE_ENV=production npm run build
      - run: npm run test-ci
        env:
          CI: true
